# Generated by Django 3.0.3 on 2020-02-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_book_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='images',
        ),
    ]
