# Generated by Django 3.0.3 on 2020-02-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_remove_book_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
